apiVersion: v1
kind: Service
metadata:
  name: app-services
spec:
  type: NodePort   
  selector:
    app: backs   
  ports:
    - name: app-port      
      protocol: TCP
      port: 5000           
      targetPort: 5000     
      nodePort: 30007     

    - name: monitoring     
      protocol: TCP
      port: 9100
      targetPort: 9100
      nodePort: 30100
