apiVersion: apps/v1
kind: Deployment
metadata:
  name: backs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backs
  template:
    metadata:
      labels:
        app: backs
    spec:
      containers:
        - name: backs
          image: eks-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
        - name: monitoring-pod-exporter
          image: quay.io/prometheus/node-exporter:latest
          ports:
            - containerPort: 9100