apiVersion: v1
kind: Service
metadata:
  name: app-services
  labels:
    app: nginx-services
    env: dev
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 80
    - name: monitoring
      port: 9100
      targetPort: 9100
  selector:
    app: nginx
    env: dev